function scr_credit(arg0, arg1, arg2 = 1) constructor
{
    header = arg0;
    text_line = arg1;
    columns = arg2;
}

function generate_credits()
{
    var credits = [];
    credits[0] = [new scr_credit([stringsetloc("-Main Artist-", "scr_credit_slash_scr_credit_gml_18_0"), stringsetloc("-Main Animator-", "scr_credit_slash_scr_credit_gml_19_0")], [stringset("Temmie Chang")])];
    credits[1] = [new scr_credit([stringsetloc("-Main Team-", "scr_credit_slash_scr_credit_gml_29_0")], [stringset("Sarah O'Donnell"), stringset("Juju (Taxiderby)"), stringset("Fred Wood"), stringset("Jean Canellas"), stringset("AlexMdle"), stringset("PureQuestion")])];
    credits[2] = [new scr_credit([stringsetloc("-Main Team-", "scr_credit_slash_scr_credit_gml_44_0_b")], [stringset("Enjl"), stringset("Joost (waddle)"), stringset("Sara Spalding (SaraJS)"), stringset("Robert Sephazon (Producer)"), stringset("Andy Brophy"), stringset("Xan Wetherall")])];
    credits[3] = [new scr_credit([stringsetloc("-Area & Fashion Concept Art-", "scr_credit_slash_scr_credit_gml_58_0")], [stringset("Gigi DG")]), new scr_credit([stringsetloc("-Platforming System Development-", "scr_credit_slash_scr_credit_gml_65_0")], [stringset("ondydev"), stringset("Enjl")]), new scr_credit([stringsetloc("-Guest Bullet Program-", "scr_credit_slash_scr_credit_gml_74_0")], [stringset("Eebrozgi")])];
    credits[4] = [new scr_credit([stringsetloc("-Flowery Intro Animation-", "scr_credit_slash_scr_credit_gml_84_0"), stringsetloc("-Director and Storyboard-", "scr_credit_slash_scr_credit_gml_85_0"), stringsetloc("-Animation Character Design-", "scr_credit_slash_scr_credit_gml_86_0"), stringsetloc("-Key Animation-", "scr_credit_slash_scr_credit_gml_87_0")], [stringsetloc("Toko Yatabe", "scr_credit_slash_scr_credit_gml_90_0_b")]), new scr_credit([stringsetloc("-In-between Animation-", "scr_credit_slash_scr_credit_gml_95_0_b")], [stringsetloc("Yasuhito Murata", "scr_credit_slash_scr_credit_gml_98_0"), stringsetloc("Mayuko Kanosue", "scr_credit_slash_scr_credit_gml_99_0")], 2), new scr_credit([stringsetloc("-Color Design-", "scr_credit_slash_scr_credit_gml_103_0"), stringsetloc("-Color Coordination Inspection-", "scr_credit_slash_scr_credit_gml_104_0")], [stringsetloc("Akiko Inoue", "scr_credit_slash_scr_credit_gml_107_0_b")])];
    credits[5] = [new scr_credit([stringsetloc("-Flowery Intro Animation Cont.-", "scr_credit_slash_scr_credit_gml_114_0"), stringsetloc("-Color Clean-up-", "scr_credit_slash_scr_credit_gml_115_0")], [stringsetloc("Wish", "scr_credit_slash_scr_credit_gml_118_0"), stringsetloc("Hikaru Takigawa", "scr_credit_slash_scr_credit_gml_119_0"), stringsetloc("Shiho Okamiya", "scr_credit_slash_scr_credit_gml_120_0")]), new scr_credit([stringsetloc("-Color Clean-up Manager-", "scr_credit_slash_scr_credit_gml_125_0")], [stringsetloc("Kosuke Kobashi", "scr_credit_slash_scr_credit_gml_128_0")]), new scr_credit([stringsetloc("-Backgrounds-", "scr_credit_slash_scr_credit_gml_132_0")], [stringsetloc("Akane Iwakuma", "scr_credit_slash_scr_credit_gml_135_0")])];
    credits[6] = [new scr_credit([stringsetloc("-Flowery Intro Animation Cont.-", "scr_credit_slash_scr_credit_gml_142_0_b"), stringsetloc("-Backgrounds Manager-", "scr_credit_slash_scr_credit_gml_143_0")], [stringsetloc("Kaoru Inamura", "scr_credit_slash_scr_credit_gml_146_0")]), new scr_credit([stringsetloc("-Filming-", "scr_credit_slash_scr_credit_gml_151_0_b")], [stringsetloc("Nanae Hirabayashi", "scr_credit_slash_scr_credit_gml_154_0")]), new scr_credit([stringsetloc("-Animation Producer-", "scr_credit_slash_scr_credit_gml_159_0_b")], [stringsetloc("Yuki Sugitani", "scr_credit_slash_scr_credit_gml_162_0")]), new scr_credit([stringsetloc("-Production Studio-", "scr_credit_slash_scr_credit_gml_166_0")], [stringsetloc("studio khara", "scr_credit_slash_scr_credit_gml_169_0")])];
    credits[7] = [new scr_credit([stringsetloc("-Guest Character Design-", "scr_credit_slash_scr_credit_gml_92_0")], [stringsetloc("(Terakota & Shinobeetle)", "scr_credit_slash_scr_credit_gml_95_0"), stringset("Nelnal"), stringsetloc("(Netskie)", "scr_credit_slash_scr_credit_gml_97_0"), stringset("Hitoshi Ariga")])];
    var pink_credits = stringsetloc("-Pink Overworld & Face Sprites-", "scr_credit_slash_scr_credit_gml_107_0");
    if (scr_flag_get(1846) < 2)
    {
        pink_credits = stringsetloc("-Secret Art-", "scr_credit_slash_scr_credit_gml_110_0");
    }
    credits[8] = [new scr_credit([stringsetloc("-Bromide Art-", "scr_credit_slash_scr_credit_gml_116_0")], [stringset("Moa"), stringset("Yukanuntiusel")]), new scr_credit([stringset(pink_credits)], [stringset("Claire Belton")]), new scr_credit([stringsetloc("-Guest Music Arrangement-", "scr_credit_slash_scr_credit_gml_131_0")], [[stringsetloc("(Garden of Hopes & Dreams)", "scr_credit_slash_scr_credit_gml_130_0")], stringset("Carlos \"insaneintherain\" Eiene")])];
    var music_credits = stringsetloc("(Cutie Mew Mew Magic)", "scr_credit_slash_scr_credit_gml_139_0");
    if (scr_flag_get(1846) < 2)
    {
        music_credits = stringsetloc("(??????)", "scr_credit_slash_scr_credit_gml_142_0");
    }
    credits[9] = [new scr_credit([stringsetloc("-Guest Music Arrangement-", "scr_credit_slash_scr_credit_gml_148_0")], [[stringsetloc("(Rakuichi Buster)", "scr_credit_slash_scr_credit_gml_151_0")], stringset("rakuichi"), [stringset(music_credits), stringsetloc("(Flower Man)", "scr_credit_slash_scr_credit_gml_160_0")], stringset("Camellia"), [stringsetloc("(Chapter 5 Credits)", "scr_credit_slash_scr_credit_gml_159_0"), stringsetloc("(Deltarune Piano Collections)", "scr_credit_slash_scr_credit_gml_160_0_b")], stringset("Trevor Alan Gomes")])];
    credits[10] = [new scr_credit([stringsetloc("-Guest Music Arrangement-", "scr_credit_slash_scr_credit_gml_148_0")], [[stringsetloc("(I guess I'm in love)", "scr_credit_slash_scr_credit_gml_173_0_b")], stringset("Itoki Hana")]), new scr_credit([stringsetloc("-Anime Cutscene SFX-", "scr_credit_slash_scr_credit_gml_90_0")], [stringset("Power-Up Audio")]), new scr_credit([stringsetloc("-Development Tools (Cool)-", "scr_credit_slash_scr_credit_gml_164_0")], [stringset("Juju Adams")])];
    credits[11] = [new scr_credit([stringsetloc("-Japanese Localization-", "scr_credit_slash_scr_credit_gml_170_0")], [stringsetloc("8-4, Ltd.", "scr_credit_slash_scr_credit_gml_173_0")]), new scr_credit([stringsetloc("-Translator-", "scr_credit_slash_scr_credit_gml_177_0")], [stringset("Keiko Fukuichi")])];
    credits[12] = [new scr_credit([stringsetloc("-Localization Producers-", "scr_credit_slash_scr_credit_gml_187_0")], [stringset("Tina Carter"), stringset("John Ricciardi")]), new scr_credit([stringsetloc("-Localization Support-", "scr_credit_slash_scr_credit_gml_195_0")], [stringset("Graeme Howard"), stringset("Hiroyuki Matsushita"), stringset("Yutaka Ohbuchi"), stringset("Sami Ragone"), stringset("JP Wentz")])];
    credits[13] = [new scr_credit([stringsetloc("-QA-", "scr_credit_slash_scr_credit_gml_231_0"), stringsetloc("DIGITAL HEARTS Co., Ltd.", "scr_credit_slash_scr_credit_gml_234_0")], [stringsetloc("Shuhei Kaji [QA Project Manager]", "scr_credit_slash_scr_credit_gml_294_0"), stringsetloc("Yu Takamori [QA Lead]", "scr_credit_slash_scr_credit_gml_295_0"), stringsetloc("Tatsuki Imai [Sales Dept]", "scr_credit_slash_scr_credit_gml_296_0")])];
    credits[14] = [new scr_credit([stringsetloc("-Japanese Graphics-", "scr_credit_slash_scr_credit_gml_221_0")], [stringset("256graph"), stringset("Satoshi Maruyama")]), new scr_credit([stringsetloc("-Super Tester-", "scr_credit_slash_scr_credit_gml_306_0")], [stringset("Esteban Criado (DruidVorse)")]), new scr_credit([stringsetloc("-Website-", "scr_credit_slash_scr_credit_gml_253_0")], [stringset("Brian Coia")]), new scr_credit([stringsetloc("-Trailers & All Video Editing-", "scr_credit_slash_scr_credit_gml_277_0")], [stringset("Everdraed")])];
    credits[15] = [new scr_credit([stringsetloc("-Special Thanks-", "scr_credit_slash_scr_credit_gml_287_0")], [stringset("Hiroko Minamoto"), stringset("Alissa Staples"), stringset("Fontworks Inc."), stringset("Yutaka Sato (Happy Ruika)"), stringsetloc("All 8-4 & Fangamer Staff", "scr_credit_slash_scr_credit_gml_293_0"), stringset("Claire & Andrew"), stringset("Brian Lee"), stringset("YoYo Games")])];
    return credits;
}
